### ISSUE TITLE
Tabs that can't be restored

### ISSUE THREAD

**Issue by brycenesbitt** [valord577/theSaferSuspender#1]
After a reboot or hibernate, I'm getting tabs that have no link for restoration.
I don't know exactly why, but it's not just a few times.

![image](https://user-images.githubusercontent.com/1294423/105317469-14046400-5b77-11eb-9719-04625a1dc60d.png)

As of the January 20th version, on Firefox for Windows 10.

**Comment by valord577** [comment]
@brycenesbitt  
Hi, What version of the plugin are you using? The latest version is [v1.4 for Firefox](https://addons.mozilla.org/en-US/firefox/addon/the-safer-suspender/).  
I have fixed a few issues. You can try again after upgrading the add-on. Or you can view [the document](https://github.com/valord577/theSaferSuspender/blob/v-firefox/CHANGE.md) for change log.  

If it is NOT useful, I will ask you something for details.

**Comment by brycenesbitt** [comment]
That is with version 1.4 of the plugin

Version
1.4
Last Updated
January 20, 2021

**Comment by valord577** [comment]
I understand.  
Due to changes the overall code logic, so the v1.4 is incompatible with the previous.  
You can open new tabs and use the add-on normally.
